[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ccrypt"
version = "0.1.0"
description = "A caesar crypt package"
authors = [
    {name = "Adam Schwartz", email = "ags613@nyu.edu"},
]
dynamic = ["version"]

